### ISSUE TITLE
System cannot find file error

### ISSUE THREAD

**Issue by DawsonG** [miracle2k/py-androidbuild#5]
Hi,
I've been working to get py-androidbuild to create a middle of the road solution between Eclipse (which is too clunky) and Ant (which is too Ant).  Unfortunately, I've hit a bit of a roadblock.  I'm running the example code against a working project that compiles correctly through Eclipse.  The console spits out:

```
E:\OSMstudios\Library\adk\platform-tools\aapt.exe package -m -M E:\OSMstudios\Project Resources\Android\Andvestigate_B\AndroidManifest.xml -S E:\OSMstudios\Project Resources\Android\Andvestigate_B\res -I E:\OSMstudios\Library\adk\platforms\android-10\android.jar -J E:\OSMstudios\Project Resources\Android\Andvestigate_B\gen
Traceback (most recent call last):
File "not-eCLIpse.py", line 429, in build_project apk = project.build()
File "build\bdist.win32\egg\android\build.py", line 550, in build
File "build\bdist.win32\egg\android\build.py", line 538, in compile
File "build\bdist.win32\egg\android\build.py", line 288, in compile
File "build\bdist.win32\egg\android\build.py", line 226, in compile_java
File "build\bdist.win32\egg\android\tools.py", line 243, in __call__
File "build\bdist.win32\egg\android\tools.py", line 76, in __call__
File "C:\Program Files (x86)\Python27\lib\subprocess.py", line 679, in __init__
errread, errwrite)
File "C:\Program Files (x86)\Python27\lib\subprocess.py", line 896, in _execute_child startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

I'm specifying a targetSdkVersion in the Manifest of 10 and the same error occurs on Windows and on Ubuntu.

This is the code
'''python
project = AndroidProject(self.project_path.GetPath() + '\AndroidManifest.xml',sdk_dir=config.sdk_path)
project.build()
''''

I've checked all of the above paths and they are correct.  I can manually reach the .bat files using subprocess.Popen.

I would appreciate any help you can provide.  Thank you.

**Comment by miracle2k** [comment]
I don't know if I ever tried this on Windows. The error message would indicate that the executable it is trying to run cannot be found. The output is easily misleading, since the logging happens after the command has been run. So it's not appt.exe that fails; instead, looking at the stacktrace, it fails to find and/or run javac.

Looking at the code, it expects javac to be in your system path. It does not consider a JAVA_HOME environment variable.

**Comment by DawsonG** [comment]
I added the Java bin to my path variable but am still getting the same error.

**Comment by miracle2k** [comment]
How familiar are you with Python? You'll might want to strategically place a few print statements to see what is going on, for example here:

https://github.com/miracle2k/py-androidbuild/blob/master/src/android/tools.py#L73

```
  print cmdline
```

That should help you get a closer idea of where the problem lies.

**Comment by DawsonG** [comment]
I changed my code to read:

```
project = AndroidProject(self.project_path.GetPath() + '\\AndroidManifest.xml',sdk_dir=config.sdk_path)
try:
    project.clean()
    project.build()
except ProgramFailedError, e:
    print e.cmdline
    print e.returncode
    print e.stderr
    print e.stdout
```

And added the logger definition at the top of the file

```
logging.getLogger('py-androidbuild').addHandler(logging.StreamHandler())
```

This is the first time I've working in Python for any extended period.  I'm mostly a Java programmer.  Could it have anything to do with line 112 in build.py?  Right now it reads:

```
javac = 'javac',
```

should it read:

```
javac = 'javac.exe' if sys.platform=='win32' else 'javac'),
```

?

I admit that I'm stumbling in the dark right now.

**Comment by DawsonG** [comment]
I made those changes to your source files, but am still receiving the error.

After further experimentation, I found that giving the full pathname to javac fixed the problem, but I'm not sure how to get this information for use on different computers.

**Comment by miracle2k** [comment]
I'm sorry, I don't have a Windows dev machine available now. To fix this, I would do two things:
- Definitively find out it is javac that fails to run (I am pretty sure it is).
- Try to see if and how you get the failing process to run via the subprocess module manually, and how that differs from what the code in tools.py does.

Things to consider:
- All the other tools are run via an absolute path.
- subprocess.Popen has a shell=True argument that cause the command to be run via cmd.exe. 
- It might also be relevant how you've added the Java bin dir to the path (via "My Computer" properties?); I'd also consider it possible that you might need reboot before that change will be picked up outside of a shell.

**Comment by DawsonG** [comment]
Thanks! The key turned out to be the shell=True command.  I sent a pull request for changes that should work on Windows and on Linux.

I appreciate all of your help.  If you have PayPal or something similar, I'd love to buy you a beer.
