### ISSUE TITLE
py-androidbuild vs gradle

### ISSUE THREAD

**Issue by IgorGanapolsky** [miracle2k/py-androidbuild#9]
Hello,
I am currently trying to migrate a huge ant-based Android project to Gradle.  This is a big undertaking.  I came across your plugin through PyCharm.  Do you think it is still worth using py-androidbuild, or should I stick to Gradle?

Thank you,
Igor

**Comment by miracle2k** [comment]
I don't know Gradle (yet), but it looks certainly more reasonable than ant, and if I were starting a new project I would strongly consider using Gradle.
